In [1]:
import tensorflow as tf 

In [2]:
constante=tf.constant([2.0,3,4],dtype=tf.float32, name='Constante1')

In [3]:
print(constante)

Tensor("Constante1:0", shape=(3,), dtype=float32)


In [4]:
apartado=tf.placeholder(tf.float32, name='Apartado1')

In [5]:
print(apartado)

Tensor("Apartado1:0", dtype=float32)


In [6]:
variable=tf.Variable(3,dtype=tf.float32,name='variable1')

In [7]:
print(variable)

<tf.Variable 'variable1:0' shape=() dtype=float32_ref>


In [8]:
matriz=tf.zeros([3, 4], tf.int32, name='matriz')

In [9]:
print(matriz)

Tensor("matriz:0", shape=(3, 4), dtype=int32)


In [10]:
inicializar=tf.global_variables_initializer()

In [11]:
sess=tf.Session()

In [12]:
sess.run(inicializar)

In [15]:
print(sess.run(variable))

3.0


In [16]:
multiplicacion=apartado*constante

In [17]:
print(sess.run(multiplicacion,feed_dict={apartado:[[15,10,5]]}))

[[ 30.  30.  20.]]


In [18]:
#Multiplicacion de matrices necesita lleva la forma (M,N)x(N,M)=M,M
a=tf.placeholder(tf.float32, shape=(2,2))
b=tf.placeholder(tf.float32, shape=(2,3))
#(2,2)x(2,3)
mult=tf.matmul(a,b)
init=tf.global_variables_initializer()
sess=tf.Session()
sess.run(init)
print(sess.run(mult,feed_dict={a:[[1,2],[2,2]],b:[[12,21,4],[3,2,4]] }))

[[ 18.  25.  12.]
 [ 30.  46.  16.]]


In [19]:
c=tf.placeholder(tf.float32, shape=(3))
d=tf.placeholder(tf.float32, shape=(3))
punto=tf.tensordot(c,d,1)
init=tf.global_variables_initializer()
sess=tf.Session()
sess.run(init)
print(sess.run(punto,feed_dict={c:[1,2,3],d:[3,2,1]}))

10.0
